### ISSUE TITLE
Support for multi colored filaments

### ISSUE THREAD

**Issue by Disane87** [Disane87/spoolman-homeassistant#150]
### Discussed in https://github.com/Disane87/spoolman-homeassistant/discussions/148

<div type='discussions-op-text'>

<sup>Originally posted by **thewolfman56** October  1, 2024</sup>
Whenever I add a multi-colored filament to Spoolman, the new spool shows up with just the nozzle icon and the theme color.  Is there something I need to do so that colors show up similar to the single-colored filaments?  Multi-colored filaments look just fine in Spoolman itself.</div>

**Comment by thewolfman56** [comment]
Just saw this in the Home Assistant Logs for my spool # 9 and #13 (which are multi-colored filaments) when I restarted Home Assistant after upgrading to 2024.10.2.

```
This error originated from a custom integration.

Logger: custom_components.spoolman.sensor
Source: custom_components/spoolman/sensor.py:70
integration: Spoolman (documentation, issues)
First occurred: 8:55:40 AM (2 occurrences)
Last logged: 8:55:40 AM

SpoolManCoordinator: Spool with ID '9' has no color_hex set. Can't create entity picture.
SpoolManCoordinator: Spool with ID '13' has no color_hex set. Can't create entity picture.
```

**Comment by Disane87** [comment]
Thank you! Will investigate it. It seems color_hex is set on spools which had a color before the implementation of multi color in spoolman. New spools only with multicolor doesn't seems to have this. 

Will consider this when I implement multi color support
