### ISSUE TITLE
"URL does not return JSON content"

### ISSUE THREAD

**Issue by Disane87** [Disane87/spoolman-homeassistant#17]
actually i input the IP (http://192.168.1.133:7912/), and leave API-Key empty and the error i get is "URL does not return JSON content"

_Originally posted by @micro-fx in https://github.com/Disane87/spoolman-homeassistant/discussions/15_

**Comment by Disane87** [comment]
When you get the message `URL does not return JSON content` it seems your spoolman really doesn't return the exppected data. You can try to grab your URL and append `api/v1/spool`. Like this (only an example: `https://spoolman.disane.dev/api/v1/spool`)

Now you should get a json with all your spools. In the code I don't do anything else:
https://github.com/Disane87/spoolman-homeassistant/blob/0155d5937b844bb7c4022f5e95a55584ff54a3e2/custom_components/spoolman/coordinator.py#L27

https://github.com/Disane87/spoolman-homeassistant/blob/0155d5937b844bb7c4022f5e95a55584ff54a3e2/custom_components/spoolman/const.py#L9

Hope this helps :)

**Comment by micro-fx** [comment]
so i added such as http://192.168.1.133:7912/api/v1/spool
and i get some json format, and includes spool info.

so what is the path i should use when adding the HA integration?

if i use the appended url when adding the integration, i get "**Failed to connect to the URL. Status code: 404**"

**Comment by Disane87** [comment]
You only need `http://192.168.1.133:7912` without trailing slash. That should work.

**Comment by Disane87** [comment]
@micro-fx I've implemented a check for missing trailing slashes. Unfortunatly there was a bug. You should install the latest version and it should work.

**Comment by micro-fx** [comment]
I can confirm it now works on the new version
![image](https://github.com/Disane87/spoolman-homeassistant/assets/48091146/a87f8fe3-a7fe-4bcf-a2b8-7d96efee935b)

**Comment by Disane87** [comment]
Great, thank you for the feedback @micro-fx! Have fun with it! If you have further questions or concerns just hit me up 🆙
