### ISSUE TITLE
IoBroker Integration

### ISSUE THREAD

**Issue by Suschibomber** [Disane87/spoolman-homeassistant#57]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Adapter iobroker Missing 

### Describe the solution you'd like

Hey Marco ist es möglich das du das ganze auch als Adapter für den iobroker zur Verfügung stellst? Das wäre echt mega 👍🏻🙏🏻🤩

### Describe alternatives you've considered

Oder vielleicht kennst du wen der das kann?!

### Additional context

Vielen Dank vorab.

**Comment by Disane87** [comment]
Leider kenne ich mich mit iO Broker überhaupt nicht aus, daher wird das zumindest von meiner Seite aus erstmal nix
