### ISSUE TITLE
KeyError on self._filament['vendor']

### ISSUE THREAD

**Issue by nervous-inhuman** [Disane87/spoolman-homeassistant#58]
## System Information

version | core-2023.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.59
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4960
Installed Version | 1.33.0
Stage | running
Available Repositories | 1336
Downloaded Repositories | 42

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 109.5 GB
disk_used | 48.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Cloudflared (4.2.10), CoreDNS (1.10.1), ESPHome (2023.11.1), File editor (5.7.0), Glances (0.20.0), Let's Encrypt (4.12.9), MariaDB (2.6.1), Mosquitto broker (fix) (6.0.2b), NGINX Home Assistant SSL proxy (3.5.0), Nginx Proxy Manager (0.12.3), Prometheus (1.0.0-beta.0), Samba share (12.1.0), Tailscale (0.13.1), TasmoAdmin (0.26.0), Terminal & SSH (9.8.1), WireGuard (0.9.0), Z-Wave JS (0.3.0), Zigbee2MQTT (1.33.2-1), rtl_433 (0.4.1), rtl_433 MQTT Auto Discovery (0.7.0), TimescaleDB (3.0.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 27
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 27, 2022 at 10:19 PM
-- | --
current_recorder_run | November 15, 2023 at 8:42 AM
estimated_db_size | 37343.92 MiB
database_engine | postgresql
database_version | 15.3

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.13
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 0
total_devices | 0

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After configuring the integration, it fails to start up with the following error:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:359
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 2:06:42 PM (2 occurrences)
Last logged: 2:06:53 PM
Error while setting up spoolman platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/spoolman/sensor.py", line 43, in async_setup_entry
    spool_device = Spool(hass, coordinator, spool_data, idx, config_entry)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spoolman/sensor.py", line 62, in __init__
    self._attr_name = f"{self._filament['vendor']['name']} {self._filament['name']} {self._filament['material']}"
                         ~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'vendor'
```

Fwiw, I do have a filament without a Vendor name, as I didn't know it's manufacturer. It's possible the code isn't handling this edge case.

### Reproduction steps

1. Install integration
2. Add integration (w/ specifying the spoolman host)
3. No devices/entities have been added

### Debug logs

```text
Sorry, I don't want to include intentionally sensitive data from all of my integrations.
```

**Comment by Disane87** [comment]
Thanks for this issue. Yeah, that seems to be a problem. Will consider that in the next release 👍🏻

**Comment by Disane87** [comment]
Unfortunatly I can't fix that. Because I use the vendor as the name of the sensor. I need this to distinguish between duplicate names (i.e. color name) with different vendors. 

https://github.com/Disane87/spoolman-homeassistant/blob/03b228cd74c4f08c09d135deb6032c438943c935/custom_components/spoolman/sensor.py#L62C11-L62C11

There could be an edge case where you have named your filaments like "Black" for different or no vendors. The only thing I could consider is to skip adding that filament if you don't have a vendor.

But IMHO setting a vendor would be the prefered solution. What do you think  @nervous-inhuman?

**Comment by Disane87** [comment]
Thank you for the idea with appending a number. I could append the spool id to the sensor name. And if the vendor is not set I could default to `no_vendor`.

But if I think about that a bit, that could lead to another problem if you add a vendor later (after the spool is already added to HA). 

Hm. I the only option for me is to generate the sensor name only with a prefix like this `spoolman_id`. That would prevent problems which renaming filaments too.

**Comment by Disane87** [comment]
I have a potential fix for that in the latest dev version. Would be nice if you can test this and get me some feedback. If it's working for you, I would release it on the stable channel :)
