### ISSUE TITLE
Do you have an example of a nice map proposed for the dashboard?

### ISSUE THREAD

**Issue by Disane87** [Disane87/spoolman-homeassistant#62]
Do you have an example of a nice map proposed for the dashboard?

_Originally posted by @Eloura74 in https://github.com/Disane87/spoolman-homeassistant/issues/61#issuecomment-1827637967_

**Comment by pdsccode** [comment]
Just for info as I struggled a bit implementing the suggested card:

I like to sort them properly by remaining weight so I added a 'numeric: true' to the sorting options:

`sort:
  method: state
  reverse: true`
