### ISSUE TITLE
Show active spool on klipper (if used)

### ISSUE THREAD

**Issue by Disane87** [Disane87/spoolman-homeassistant#86]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I want to show the current active spool in HA

### Describe the solution you'd like

Active spool can be achived by calling the klipper endpoint `https://[klipper url]/server/spoolman/spool_id` with a sample result:
```json
{
    "result": {
        "spool_id": 28
    }
}
``` 

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by PeteCondliffe** [comment]
I'm probably missing something here but how would I make this work form multiple instances?
I can see if i go to https://[klipper url]:port/server/spoolman/spool_id on each instance i get the correct spool ID's but there appears to be no way of pulling more than one instance into HA
Thanks

**Comment by Disane87** [comment]
Multiple instances are totally untested. Please open up a discussion for that. Thank you!
